### PR TITLE
Orderlies & Map Edits

### PR DESCRIPTION
**Pull request by ProbablyCarl**
- - -
Balance:
 - Jet & Turbo can now be recycled, as they're 'inhalers' instead of patches.
 - Mining now kicks up dust that you require a face covering to avoid.
 - Radaway is now considered a chempack, instead of a bloodbag.
 - You can no longer throw things, or yourself, through bars. A window version is instead included to use for this purpose. Credits to CB for the idea of something so simple, lol
 - MedX is now as intended to be used, intravenously only.
- - -
Other:
 - GMB flags and graffiti scattered around their stomping grounds.
 - DFS graffiti scattered around their main location.
 - 'Space Drugs' refluffed to 'LSD'.
 - 'Electronic Firing Pins' are now just 'Firing Pins'.
- - -
Map:
 - Minor map changes made for fluff purposes.
- - -
Icons:
 - New drug sprites, courtesy of Obey.
- - -

### CODE REVIEW

**Comment by ProbablyCarl** [comment]
- - -
Player facing:
 - New emotes.
 - Emote sounds properly added for the following:
  - Yawning
  - Pain
 - Jukebox access granted.
 - PDA lights fixed.
 - Various medical items such as sutures and ointment now provide pain / shock on use. Try not to spam them unless needed.
 - Hostile mobs no longer infight unless specifically intended to do so.
 - Sounds properly returned to various injectors.
 - Pain screens now properly apply.
 - Many map edits.
- - -
Other:
 - Medical stacks separated by file.
 - VT HQ renames.
 - get_all_jobs now includes Hilltop roles.
- - -

**Comment by ProbablyCarl** [comment]
- - -
Main:
 - Teaching of specific traits enabled.
 - Tavern Staff loadout added to Townie.
 - Various spelling mistakes fixed.
 - Some map edits.
 - Ammo bag fixes.
 - Light armour correction.
 - Proper growth states for flora.
- - -

**Comment by ProbablyCarl** [comment]
Laser weaponry added to the loot tables. Kind of.
Still super rare and shouldn't be a common thing to see for obvious reasons.

**Review by Cupax3 — APPROVED** [review]
LGTM™

**Pull request merged**
